import Footer from "@/components/footer"
import Header from "@/components/header"
import "./global.css"

import { Metadata } from "next"

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// Metadata using object
export const metadata : Metadata = {
  title: {
    // absolute:"", // check in blog route
    default:"NextJS SS",
    template:"%s | SS"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}

        <Footer />


      </body>
    </html>
  )
}
